language: generic
sudo: required
services:
  - docker
env:
  global:
    - secure: "qI0QEOmT3P3x9MfWwY0F43CxV8MRvuYDUtGRXIXs1Utpk/1wJv4zsebyHabuusEai9QakRo1kexwAuAcbyeiFTXKwn8DKIId2BDx14/fzmHSsyj86W1Tao5HAoD4NDQReI+c3LX5ipDtInlBXip0NgMMmQiT4+IzVkf9itAewCg="
    - ENCRYPTION_LABEL="1536cf00117f"
script:
  - cd .. &&
    git clone https://github.com/whatwg/html-build.git html-build &&
    bash html-build/ci-deploy/outside-container.sh
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: always
