name: Build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - github-actions # FIXME
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: shellcheck review-draft.sh
    - uses: docker://whatwg/html-deploy:latest
      env:
        HTML_SOURCE: /github/workspace # FIXME
        SERVER: ${{ secrets.MARQUEE_SERVER }}
        SERVER_PUBLIC_KEY: ${{ secrets.MARQUEE_PUBLIC_KEY }}
        SERVER_DEPLOY_KEY: ${{ secrets.MARQUEE_DEPLOY_KEY }}
